// Generated by scripts/gen-tokens.mjs from design/tokens.json — do not edit.
package garden.vayne.chorus.designsystem

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

data class ChorusPalette(
    val bg: Color,
    val surface: Color,
    val surface2: Color,
    val surface3: Color,
    val line: Color,
    val ink: Color,
    val ink2: Color,
    val ink3: Color,
    val accent: Color,
    val accentSoft: Color,
    val ok: Color,
    val warn: Color,
    val danger: Color,
)

object Tokens {
    val Light = ChorusPalette(
        bg = Color(0xFFFBF7F2),
        surface = Color(0xFFFFFFFF),
        surface2 = Color(0xFFF4EDE4),
        surface3 = Color(0xFFEADFD2),
        line = Color(0xFFE4D8CA),
        ink = Color(0xFF2B2521),
        ink2 = Color(0xFF6F6259),
        ink3 = Color(0xFFA09184),
        accent = Color(0xFFC0694E),
        accentSoft = Color(0xFFF6E1D8),
        ok = Color(0xFF5E8C61),
        warn = Color(0xFFC99A3B),
        danger = Color(0xFFB5524A),
    )
    val Dark = ChorusPalette(
        bg = Color(0xFF1B1714),
        surface = Color(0xFF231E1A),
        surface2 = Color(0xFF2B2520),
        surface3 = Color(0xFF362E28),
        line = Color(0xFF3A322B),
        ink = Color(0xFFF1E9E0),
        ink2 = Color(0xFFBCAEA1),
        ink3 = Color(0xFF85776B),
        accent = Color(0xFFE08A6D),
        accentSoft = Color(0xFF3E2A22),
        ok = Color(0xFF86B489),
        warn = Color(0xFFE0B560),
        danger = Color(0xFFE07C72),
    )
    val radiusSm = 8.dp
    val radiusMd = 14.dp
    val radiusLg = 20.dp
    val radiusFull = 999.dp
    val space1 = 4.dp
    val space2 = 8.dp
    val space3 = 12.dp
    val space4 = 16.dp
    val space5 = 20.dp
    val space6 = 24.dp
    val space8 = 32.dp
    val space12 = 48.dp
    const val motionFast = 150
    const val motionBase = 200
    const val motionSlow = 280
}
