// Emits /sw.js at build time with the exact list of built assets, so the app shell (and the
// wasm core) work offline after the first load (docs/CLIENTS.md §4.1). Dev builds get no SW.
import type { Plugin } from 'vite';

const SW = (version: string, assets: string[]) => `// generated by plugins/service-worker.ts
const CACHE = 'chorus-${version}';
const ASSETS = ${JSON.stringify(assets)};

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener('activate', (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('chorus-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (e) => {
  const url = new URL(e.request.url);
  if (e.request.method !== 'GET' || url.origin !== location.origin || url.pathname.startsWith('/api/')) return;
  if (e.request.mode === 'navigate') {
    // the app is a single page: any path (including /i/<invite>) is index.html
    e.respondWith(fetch(e.request).catch(() => caches.match('/index.html')));
    return;
  }
  e.respondWith(caches.match(e.request).then((hit) => hit || fetch(e.request)));
});

// Web Push (push.rs): switch and chat notifications while no Chorus tab is open. The server
// encrypts; the browser decrypts before we see e.data. {"t":"sync"} means "too big, come look".
self.addEventListener('push', (e) => {
  let d = {};
  try { d = e.data ? e.data.json() : {}; } catch (_) {}
  const tickle = d.t === 'sync';
  const url = d.channel_id ? '/#/chat/' + d.channel_id : '/#/people';
  e.waitUntil(self.registration.showNotification(tickle ? 'Chorus' : (d.title || 'Chorus'), {
    body: tickle ? 'Something new is waiting in Chorus.' : (d.text || ''),
    tag: d.id || undefined,
    icon: '/icon.svg',
    data: { url },
  }));
});

self.addEventListener('notificationclick', (e) => {
  e.notification.close();
  const url = (e.notification.data && e.notification.data.url) || '/';
  e.waitUntil(self.clients.matchAll({ type: 'window', includeUncontrolled: true }).then((tabs) => {
    const tab = tabs.find((t) => 'focus' in t);
    if (tab) return tab.navigate(url).then((t) => (t || tab).focus());
    return self.clients.openWindow(url);
  }));
});
`;

export function serviceWorker(): Plugin {
  return {
    name: 'chorus-service-worker',
    apply: 'build',
    generateBundle(_opts, bundle) {
      const files = Object.keys(bundle).filter((f) => !f.endsWith('.map'));
      const assets = ['/', '/index.html', '/manifest.webmanifest', '/icon.svg', ...files.map((f) => `/${f}`)];
      const version = Date.now().toString(36);
      this.emitFile({ type: 'asset', fileName: 'sw.js', source: SW(version, [...new Set(assets)]) });
    },
  };
}
