// chorus-core (Rust) for Android: UniFFI Kotlin bindings + native libs, both generated by
// scripts/build-android-core.ps1 (bindings in src/main/kotlin/uniffi, libs in src/main/jniLibs).
import java.io.File

plugins {
    alias(libs.plugins.android.library)
    alias(libs.plugins.kotlin.android)
}

android {
    namespace = "garden.vayne.chorus.core"
    compileSdk = 36
    defaultConfig { minSdk = 29 }
    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = "17" }
}

dependencies {
    // UniFFI's Kotlin bindings call into the .so through JNA
    api("${libs.jna.get()}@aar")
    testImplementation(libs.junit)
    testImplementation(libs.jna) // plain jar for JVM unit tests
}

// JVM unit tests load the host build of chorus-ffi (target/debug) through the same bindings.
tasks.withType<Test>().configureEach {
    val cargoTarget = System.getenv("CARGO_TARGET_DIR")?.let { File(it) } ?: rootProject.file("../target")
    val profile = if (System.getenv("CHORUS_FFI_PROFILE") == "release") "release" else "debug"
    systemProperty("jna.library.path", cargoTarget.resolve(profile).absolutePath)
}
