// Generate platform token files from design/tokens.json (DESIGN.md §1).
//   node scripts/gen-tokens.mjs
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const t = JSON.parse(readFileSync(join(root, 'design/tokens.json'), 'utf8'));
const header = '/* Generated by scripts/gen-tokens.mjs from design/tokens.json — do not edit. */\n';

const vars = (o, prefix, unit = '') =>
  Object.entries(o).map(([k, v]) => `  --${prefix}${k}: ${typeof v === 'number' ? v + unit : v};`).join('\n');
const colors = (o) => vars(o, '');

const css = `${header}
:root {
${colors(t.color.light)}
${vars(t.radius, 'r-', 'px')}
${vars(t.space, 's-', 'px')}
${vars(t.size, 'fs-', 'px')}
  --font-body: ${t.font.body};
  --font-display: ${t.font.display};
  --font-mono: ${t.font.mono};
  --t-fast: ${t.motion.fast}ms;
  --t-base: ${t.motion.base}ms;
  --t-slow: ${t.motion.slow}ms;
  --ease: ${t.motion.ease};
  --shadow-pop: ${t.shadow.pop};
  color-scheme: light;
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme='light']) {
${colors(t.color.dark).replaceAll('  --', '    --')}
    color-scheme: dark;
  }
}
:root[data-theme='dark'] {
${colors(t.color.dark)}
  color-scheme: dark;
}
`;
const cssPath = join(root, 'web/src/lib/design/tokens.css');
mkdirSync(dirname(cssPath), { recursive: true });
writeFileSync(cssPath, css);

const kname = (k) => k.replace(/-(\w)/g, (_, c) => c.toUpperCase());
const kcolor = (h) => `Color(0xFF${h.slice(1).toUpperCase()})`;
const palette = (name, o) =>
  `    val ${name} = ChorusPalette(\n${Object.entries(o).map(([k, v]) => `        ${kname(k)} = ${kcolor(v)},`).join('\n')}\n    )`;
const kt = `// Generated by scripts/gen-tokens.mjs from design/tokens.json — do not edit.
package garden.vayne.chorus.designsystem

import androidx.compose.ui.graphics.Color
import androidx.compose.ui.unit.dp

data class ChorusPalette(
${Object.keys(t.color.light).map((k) => `    val ${kname(k)}: Color,`).join('\n')}
)

object Tokens {
${palette('Light', t.color.light)}
${palette('Dark', t.color.dark)}
${Object.entries(t.radius).map(([k, v]) => `    val radius${k[0].toUpperCase() + k.slice(1)} = ${v}.dp`).join('\n')}
${Object.entries(t.space).map(([k, v]) => `    val space${k} = ${v}.dp`).join('\n')}
    const val motionFast = ${t.motion.fast}
    const val motionBase = ${t.motion.base}
    const val motionSlow = ${t.motion.slow}
}
`;
const ktDir = join(root, 'android/designsystem/src/main/kotlin/garden/vayne/chorus/designsystem');
if (existsSync(join(root, 'android'))) {
  mkdirSync(ktDir, { recursive: true });
  writeFileSync(join(ktDir, 'Tokens.kt'), kt);
}
console.log('tokens written');
